-- 일련번호 테이블 생성 SQL
CREATE TABLE `test_seq` (
	`SEQ` BIGINT(20) NOT NULL DEFAULT '1',
	`REFERENCE_DATE` DATE NOT NULL
)
COMMENT='Test Sequence Table'
COLLATE='utf8_general_ci'
ENGINE=MyISAM
;

-- 현재 일련번호 반환 DB 함수
CREATE DEFINER=`root`@`localhost` FUNCTION `GET_SEQ_CURRENT_VALUE`()
RETURNS bigint(20)
LANGUAGE SQL
NOT DETERMINISTIC
MODIFIES SQL DATA
SQL SECURITY DEFINER
COMMENT 'return current value'
BEGIN
DECLARE val BIGINT;
DECLARE today INT;

	SELECT DATEDIFF(REFERENCE_DATE, CURRENT_DATE()) INTO today FROM TEST_SEQ;
	
	IF today < 0 THEN
		UPDATE TEST_SEQ SET SEQ = 1, REFERENCE_DATE = NOW();
	END IF;

	SELECT SEQ INTO val FROM TEST_SEQ;
	return val;
END
;

-- 다음 일련번호 반환 DB 함수
CREATE DEFINER=`root`@`localhost` FUNCTION `GET_SEQ_NEXT_VALUE`()
RETURNS bigint(20)
LANGUAGE SQL
NOT DETERMINISTIC
MODIFIES SQL DATA
SQL SECURITY DEFINER
COMMENT 'return next sequence'
BEGIN
DECLARE val BIGINT;
DECLARE today INT;
	
	SELECT DATEDIFF(REFERENCE_DATE, CURRENT_DATE()) INTO today FROM TEST_SEQ;
	
	IF today < 0 THEN
		UPDATE TEST_SEQ SET SEQ = 1, REFERENCE_DATE = NOW();
		SET val = 1;
	else
		SELECT SEQ INTO val FROM TEST_SEQ;
		SET val = val + 1;
		UPDATE TEST_SEQ SET SEQ = val;
	end if;
	
	return val;
END
;

-- 테스트
INSERT INTO TEST_SEQ (SEQ, REFERENCE_DATE) VALUES (1, NOW()); 
SELECT GET_SEQ_CURRENT_VALUE();  
SELECT GET_SEQ_NEXT_VALUE(); 

SELECT CONCAT(DATE_FORMAT(NOW(), '%Y%m%d'),  LPAD('000' + GET_SEQ_NEXT_VALUE(), 4, 0))
FROM DUAL
;

SELECT CONCAT('ABC', DATE_FORMAT(NOW(), '%Y%m%d'),  LPAD('000' + GET_SEQ_NEXT_VALUE(), 4, 0))
FROM DUAL
;